=== Luis-3M/TheScript-XML/Content/guiao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Luis Moreira up201102786@fc.up.pt -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- GROUPS -->
	<xs:group name="hierarquia">
		<xs:choice>
			<xs:element ref="temporadas" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="partes" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="episódios" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="cenas" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:group>

	<xs:group name="preâmbulo">
		<xs:sequence>
			<xs:element name='título' type="NormString" />
			<xs:element name='sinopse' type="NormString" minOccurs="0" />
			<xs:element name="personagens" type="Personagens"
				minOccurs="0" />
		</xs:sequence>
	</xs:group>

	<!-- SIMPLE TYPES -->
	<xs:simpleType name="NormString">
		<xs:restriction base="xs:normalizedString"></xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Date">
		<xs:restriction base="xs:date"></xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Id">
		<xs:restriction base="xs:ID"></xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="IdRef">
		<xs:restriction base="xs:IDREF"></xs:restriction>
	</xs:simpleType>

	<!-- COMPLEX TYPES -->
	<xs:element name='guião'>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cabeçalho" type="Cabeçalho"></xs:element>
				<xs:group ref="hierarquia"></xs:group>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Cabeçalho">
		<xs:sequence>
			<xs:element name='título' type="NormString" />
			<xs:element name='autor' type="NormString" maxOccurs="unbounded" />
			<xs:element name='data' type="Date" />
			<xs:element name='sinopse' type="NormString" minOccurs="0" />
			<xs:element name='personagens' type="Personagens" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Personagens">
		<xs:sequence>
			<xs:element name='personagem' type="Personagem" maxOccurs='unbounded' />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Personagem">
		<xs:sequence>
			<xs:element name='nome' type="NormString" />
			<xs:element name='descrição' type="NormString" />
		</xs:sequence>
		<xs:attribute name='identificador' type="Id" use='required' />
	</xs:complexType>

	<xs:element name='temporadas'>
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="preâmbulo"></xs:group>
				<xs:element ref='episódios' maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name='identificador' type="Id" use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='episódios'>
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="preâmbulo"></xs:group>
				<xs:element ref="cenas" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name='identificador' type="Id" use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='partes'>
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="preâmbulo"></xs:group>
				<xs:element ref="cenas" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name='identificador' type="Id" use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='cenas'>
		<xs:complexType mixed='true'>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name='fala' type="Fala" />
				<xs:element name='adereço' type="NormString" />
				<xs:element name='refere' type="Refere" />
				<xs:element name='comentário' type="NormString" />
			</xs:choice>
			<xs:attribute name="contexto" type="NormString" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Fala" mixed='true'>
		<xs:attribute name="personagem" type="IdRef" use="required" />
	</xs:complexType>

	<xs:complexType name="Refere">
		<xs:attribute name="personagem" type="IdRef" use="required" />
	</xs:complexType>
</xs:schema>

=== Luis-3M/TheScript-XML/Content/guiao_curta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>

<guião xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="guiao.xsd">
	<cabeçalho>
		<título>O DEZ: O PRESENTE</título>
		<autor>João Nunes</autor>
		<data>2008-10-13</data>
		<personagens>
			<personagem identificador="personagem1">
				<nome>Edgar</nome>
				<descrição>Um homem do quotidiano que trabalha num posto de gasolina.</descrição>
			</personagem>
			<personagem identificador="personagem2">
				<nome>O Chefe</nome>
				<descrição>Nesta curta metragem a personagem "O Chefe" é exatamente isso, o
					chefe de Edgar e dono do posto de gasolina.</descrição>
			</personagem>
		</personagens>
	</cabeçalho>
	<cenas contexto="Ext. Rua de subúrbios; Amanhecer">
		Um homem caminha
		numa rua escura, em que a primeira luz da manhã
		aparece por trás da
		linha
		dos prédios.
		<fala personagem="personagem1">Às vezes gostava de ser outra pessoa; de ter
			uma vida mais simples. Não ter de ir para o trabalho à hora a que
			os outros regressam a casa.
		</fala>
		O homem é Edgar, quarenta anos,
		magro, triste. Caminha de cabeça baixa
		e mãos nos bolsos.
	</cenas>
	<cenas contexto="Int. Autocarro; Dia">
		<comentário>começa a chover</comentário>
		De cabeça encostada
		à janela, num autocarro suburbano quase vazio,
		Edgar olha sem
		expressão
		as paisagens escuras que passam a correr.
		<fala personagem="personagem2">
			Não ter que levar todos os dias com quatro
			horas de transportes
			públicos.
		</fala>
	</cenas>
	<cenas contexto="Int. Posto de gasolina; Dia">
		<adereço>Roupa de trabalho</adereço>
		<refere personagem="personagem1" />
		Está de pé em frente do balcão de um posto de abastecimento. Está
		fardado com a farda de empregado, e tem a cabeça baixa e as mãos
		atrás das costas.
		<fala personagem="personagem1">E, sobretudo, não ter de aturar a besta do
			meu
			chefe.
		</fala>
		Só agora ouvimos, de repente, o SOM AMBIENTE, no qual se destacam os
		IMPROPÉRIOS do chefe, que ainda não vemos.
		<fala personagem="personagem2">Mas será assim tão difícil de entender, ó Edgar?
		</fala>
		O CHEFE é um homem baixo, de ar duro, vestido com a versão mais
		chique da mesma farda. Bate com o dedo num bloco de notas que tem na
		mão, enquanto olha para Edgar.
		<fala personagem="personagem2">Ou é você que é particularmente burro?</fala>
		Edgar não responde nem levanta o olhar. O chefe continua a
		massacrá-lo.
		<fala personagem="personagem2">Quantas vezes vai ser preciso eu dizer-lhe que
			as referências AZ-37- nove-nove-barra-42 só são processadas depois
			das 85-três-três- barra-26? E que só depois de terminar essas duas
			é que passa para as 16-cinco-cinco-barra-91 ?
		</fala>
	</cenas>
</guião>

=== Luis-3M/TheScript-XML/Content/guiao_teatro.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>

<guião xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="guiao.xsd">
	<cabeçalho>
		<título>Auto da Barca do Inferno</título>
		<autor>Gil Vicente</autor>
		<data>1531-05-13</data>
		<sinopse>Auto da Barca do Inferno, Obra de Gil Vicente que consegue se mostrar
			contemporânea. Não é á toa que o livro “Auto da Barca do Inferno” de Gil Vicente, um
			clássico da literatura, seja obrigatório, ele retrata a sociedade portuguesa
			do século XVI e ao mesmo tempo possui temas atuais, com uma boa sátira à sociedade.
			O Auto é uma peça teatral, divida em cenas e atos, escrita em 1517. O cenário desta
			obra é um porto onde se encontram duas barcas, uma leva ao inferno e a outra ao
			paraíso, uma guiada por um Diabo e a outra por um Anjo, e sendo da decisão deles quem
			entra ou não em suas barcas.</sinopse>
		<personagens>
			<personagem identificador="personagem1">
				<nome>Diabo</nome>
				<descrição>Condutor das almas ao Inferno, conhece muito bem cada um dos
					personagens que lhe cai às mãos. Diabo é a figura que recebe todos com simpatia,
					que abre um espaço para as almas se defenderem e ironiza as suas falas.</descrição>
			</personagem>
			<personagem identificador="personagem2">
				<nome>Fidalgo</nome>
				<descrição>Representa a nobreza, e chega com um pajem, tem um vestuário
					exagerado e uma cadeira de espaldar, elementos característicos do seu estado
					social, e acaba indo para o Inferno.</descrição>
			</personagem>
			<personagem identificador="personagem3">
				<nome>Anjo</nome>
				<descrição>É uma figura fria, calada, autoritária, que se manifesta apenas
					para julgar conduzindo as almas para o Céu.</descrição>
			</personagem>
			<personagem identificador="personagem4">
				<nome>Onzeneiro</nome>
				<descrição>Figura que ao chegar à barca do Diabo descobre que seu rico dinheiro
					ficara em terra.</descrição>
			</personagem>
		</personagens>
	</cabeçalho>
	<partes identificador="parte1">
		<título>Parte I</título>
		<personagens>
			<personagem identificador="personagem0">
				<nome>Companheiro do Diabo</nome>
				<descrição>Assiste o Diabo na barca.</descrição>
			</personagem>
		</personagens>
		<cenas contexto="Junto à barca do Diabo; Dia">
			<fala personagem="personagem1">À barca, à barca, venham lá! Que temos
				gentil maré!
			</fala>
			<comentário>Dirigindo-se ao companheiro</comentário>
			<fala personagem="personagem1">Ora põe o barco à ré!</fala>
			<fala personagem="personagem0">Está feito, está feito!</fala>
			<fala personagem="personagem1">Bem feito está! Vai agora, em má hora,
				esticar aquele palanco e desocupar aquele banco, para a gente que
				virá.
			</fala>
			<comentário>Falando para o ar</comentário>
			<fala personagem="personagem1">À barca, à barca, hu-u! Depressinha, que se
				quer ir! Oh, que tempo para partir, Louvores a Belzebu!
			</fala>
			<comentário>Dirigindo-se ao companheiro</comentário>
			<fala personagem="personagem1">Mas então! que fazes tu? Limpa todo aquele
				leito!
			</fala>
			<fala personagem="personagem0">Em boa hora! Feito, feito!</fala>
			<fala personagem="personagem1">Abaixa-me esse cu! Liberta aquela poja e
				afrouxa aquela driça.
			</fala>
			<fala personagem="personagem0">Oh-oh, caça! Oh-oh, iça, iça!</fala>
			Aproxima-se o Fidalgo e, chegando ao barco infernal, diz:
			<fala personagem="personagem2">Esta barca para onde vai, que assim está
				apercebida?
			</fala>
			<fala personagem="personagem1">Vai para a ilha perdida, e há de partir daqui
				a nada.
			</fala>
			<fala personagem="personagem2">E para lá vai a senhora?</fala>
			<fala personagem="personagem1">Sou um senhor, ao vosso serviço.</fala>
			<fala personagem="personagem2">Parace-me isto um cortiço...</fala>
			<fala personagem="personagem1">Porque a vedes daí de fora.</fala>
			<fala personagem="personagem2">Pois sim, e porque terra passais?</fala>
			<fala personagem="personagem1">Para o inferno, senhor.</fala>
			<fala personagem="personagem2">Para a outra barca me vou!</fala>
		</cenas>
		<cenas contexto="Junto à barca do Anjo; Dia">
			<comentário>Já ao pé da outra barca.</comentário>
			<fala personagem="personagem2">Oh da barca! Para onde ís? Oh, barqueiros!
				Não me ouvis? Respondei-me! Olá! Ó!...
			</fala>
			<comentário>O Anjo ignora-o</comentário>
			<fala personagem="personagem2">Por deus, aviado estou! Quanto a isto é já
				pior... Que jericocins, salvanor! Pensam que eu sou um grou?
			</fala>
			<fala personagem="personagem3">Que quereis?</fala>
			<fala personagem="personagem2">Que me digais, pois morri tão sem aviso, se a
				barca do Paraíso é esta em que navegais.
			</fala>
			<fala personagem="personagem3">É esta que desejais?</fala>
			<fala personagem="personagem2">Que me deixeis embarcar. Sou fidalgo de solar,
				é bom que me recolhais.
			</fala>
			<fala personagem="personagem3">Não se embarca tirania, neste batel divinal.
			</fala>
			<fala personagem="personagem2">Não sei porque negais entrada à minha
				senhoria...
			</fala>
			<fala personagem="personagem3">Para a vossa fantasia muito pequena é esta
				barca.
			</fala>
			<fala personagem="personagem2">Para senhor de bom nome, não há aqui mais
				cortesia? Venha a prancha e atavio! Levai-me desta ribeira!
			</fala>
			<fala personagem="personagem3">Não vindes cá a pensar de entrar neste navio.
				Aquele ali vai mais vazio. Ali a cadeira entrará, o rabo caberá e
				todo vosso senhorio. Ireis ali mais espaçoso, vossa fumosa
				senhoria, a pensar na vossa tirania
				Contra o pobre povo queixoso. E
				porque, de generoso, desprezaste os pequenos, achar-vos-ei tanto
				menos Quanto mais foste fumoso.
			</fala>
		</cenas>
	</partes>
	<partes identificador="parte2">
		<título>Parte II</título>
		<cenas contexto="Junto à barca do Diabo; Tarde">
			Aparece um Onzeneiro, e pergunta ao barqueiro do Inferno, dizendo:
			<fala personagem="personagem4">Para onde navegais?</fala>
			<fala personagem="personagem1">Oh! Em que má hora chegais, Onzeneiro, meu
				parente! Porque tardastes vós tanto?
			</fala>
			<fala personagem="personagem4">Mais ainda eu quisera tardar...
				Na safra do
				apanhar, deu-me Saturno o quebranto.
			</fala>
			<fala personagem="personagem1">Ora muito me espanto por ver não vos salvar o
				dinheiro!...
			</fala>
			<fala personagem="personagem4">Nem para o barqueiro me deixaram ficar com
				algo...
			</fala>
			<fala personagem="personagem1">Ora então entrai, entrai aqui!</fala>
			<fala personagem="personagem4">Não hei eu de aí embarcar!</fala>
			<fala personagem="personagem1">Oh! Que gentil recear, e que divertido para
				mim!
			</fala>
			<fala personagem="personagem4">Ainda agora faleci! Deixa-me escolher um batel!
			</fala>
			<fala personagem="personagem1">Oh São Pimentel! Porque não irás aqui?</fala>
			<fala personagem="personagem4">E para onde é a viagem?</fala>
			<fala personagem="personagem1">É para onde tu hás de ir.</fala>
			<fala personagem="personagem4">E vamos já partir?</fala>
			<fala personagem="personagem1">Não penses em mais linguagem.</fala>
			<fala personagem="personagem4">Mas para onde é a passagem?</fala>
			<fala personagem="personagem1">Para a infernal comarca.</fala>
			<fala personagem="personagem4">Dix! Não vou eu em tal barca. Aquela outra tem
				avantagem.
			</fala>
		</cenas>
		<cenas contexto="Junto à barca do Anjo">
			Dirige-se à barca do Anjo, e diz:
			<fala personagem="personagem4">Oh da barca! Olá! Ó! Haveis já de partir?
			</fala>
			<fala personagem="personagem3">E onde queres tu ir?</fala>
			<fala personagem="personagem4">Eu, para o Paraíso vou.</fala>
			<fala personagem="personagem3">Pois quanto a mim, muito fora estou de te levar
				para lá. Aquela outra barca te aceitará. Ali vai quem enganou!
			</fala>
			<fala personagem="personagem4">Porquê?</fala>
			<fala personagem="personagem3">Porque esse bolsão ocuparia todo o navio.
			</fala>
			<fala personagem="personagem4">Juro a Deus que vai vazio!</fala>
			<fala personagem="personagem3">Não no teu coração.</fala>
			<fala personagem="personagem4">Lá me ficou de roldão a minha fazenda e alheia.
			</fala>
			<fala personagem="personagem3">Ó onzena, como és feia e filha da maldição!
			</fala>
		</cenas>
	</partes>
</guião>

=== Luis-3M/TheScript-XML/Content/guiao_serie.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>

<guião xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="guiao.xsd">
	<cabeçalho>
		<título>Mr. Robot</título>
		<autor>Sam Esmail</autor>
		<data>2015-06-24</data>
		<sinopse>Mr. Robot follows Elliot, a young programmer who works as a
			cyber-security engineer by day and a vigilante hacker by night. Elliot finds
			himself at a crossroad when the mysterious leader of an underground hacker group
			recruits him to destroy the corporation he is paid to protect.</sinopse>
		<personagens>
			<personagem identificador="personagem1">
				<nome>Elliot Alderson</nome>
				<descrição>Rami Malek was born on May 12, 1981 in Los Angeles, California, USA
					as Rami Said Malek. He is an actor, known for Short Term 12 (2013), Need for Speed
					(2014) and Mr. Robot (2015).</descrição>
			</personagem>
			<personagem identificador="personagem2">
				<nome>Mr. Robot</nome>
				<descrição>Christian Michael Leonard Slater was born on August 18, 1969 in New
					York City, to Michael Hawkins, a well-known soap actor, and Mary Jo Slater (née
					Lawton), a casting agent. Christian started in show business early,
					appearing on the soap opera The Edge of Night (1956) in 1976 at the age of 7.</descrição>
			</personagem>
		</personagens>
	</cabeçalho>
	<temporadas identificador="temporada1">
		<título>Season 1</título>
		<episódios identificador="episódio1.1">
			<título>Hello Friend</título>
			<sinopse>Elliot, a cyber-security engineer by day and vigilante hacker by
				night, is recruited by a mysterious underground group to destroy the firm he's
				paid to protect. Elliot must decide how far he'll go to expose the forces he
				believes are running (and ruining) the world.</sinopse>
			<cenas contexto="Junto ao parque de diversões; Dia">
				<fala personagem="personagem2">Eliot, consegui o último saquinho de Twinkies
					do mercado. Queres um?
				</fala>
				<fala personagem="personagem1">Ela acabou de me chamar espantalho.</fala>
			</cenas>
			<cenas contexto="Na roda gigante; Dia">
				<fala personagem="personagem1">Foi por isso que me escolheste a mim, porque
					eu trabalho na AllSafe.
				</fala>
				<fala personagem="personagem2">Amanhã a AllSafe vai receber uma visita do
					FBI
					e do Comando Cibernético Americano.
				</fala>
			</cenas>
		</episódios>
		<episódios identificador="episódio1.2">
			<título>Ones and Zeros</título>
			<sinopse>Elliot is torn between accepting a job offer from Evil Corp and joining
				the fsociety hacker group. At the same time Elliot needs to make decision that
				could harm people around him.</sinopse>
			<cenas contexto="Em casa de Elliot; Noite">
				<fala personagem="personagem1">Estou a violar a minha regra mas é uma semana
					estranha.
				</fala>
			</cenas>
		</episódios>
	</temporadas>
	<temporadas identificador="temporada2">
		<título>Season 2</título>
		<personagens>
			<personagem identificador="personagem3">
				<nome>Elliot's Mother</nome>
				<descrição>Vaishnavi Sharma is an actress, known for Anjali (2008), Mr. Robot
					(2015) and Rasikan Re (2003).</descrição>
			</personagem>
		</personagens>
		<episódios identificador="episódio2.1">
			<título>Unm4sk-pt1</título>
			<sinopse>A brief flashback shows that Tyrell recorded an fsociety video the
				night he visited Elliot. One month later, Elliot has gone off the grid, living
				with his mother and maintaining a repetitive routine in an attempt to weaken the
				influence of Mr. Robot, who continually appears to him and torments him while
				still refusing to tell him what happened to Tyrell. fsociety continues under
				Darlene's leadership, hacking the smart home of E Corp general counsel Susan
				Jacobs and using it as home base after forcing Jacobs to move out. With Mobley's
				assistance, Darlene executes a hack on the Bank of E Corp, holding their records
				for ransom.</sinopse>
			<cenas contexto="Em casa da mãe de Elliot; Crepúsculo">
				<refere personagem="personagem1" />
				Tenho mantido um diário. É a única forma de manter o meu programa a
				correr, como é suposto.
				<comentário>O dia anoitece</comentário>
				<fala personagem="personagem3">Vejo-te de manhã.</fala>
				E depois vou para a cama. A minha mãe não tem computador ou acesso à
				Internet para tentar-me durante a noite.
			</cenas>
		</episódios>
		<episódios identificador="episódio2.2">
			<título>Unm4sk-pt2</título>
			<sinopse>Fsociety blackmails Scott Knowles into publicly burning $5.9
				million cash for the ransom (of the hack of the previous episode) while wearing
				an fsociety mask. Angela continues up the ladder at E Corp, seemingly content in
				her new corporate position, and appears to abandon the lawsuit. Joanna
				receives a gift on her doorstep, a music box with a phone hidden underneath, but
				misses the call. Elliot discovers he has been acting under Mr. Robot's
				influence while he thought he was sleeping. A man named Brock murders Gideon,
				who had earlier threatened to report Elliot's suspicious behavior at Allsafe
				to the FBI and agent Dominique DiPierro. Elliot wakes up from a dissociative
				state on the phone, greeted on the other end by Tyrell. </sinopse>
			<cenas contexto="Junto ao telefone; Noite">
				<fala personagem="personagem1">
					Quero saber o que aconteceu, diz-me o que
					aconteceu!
				</fala>
				<fala personagem="personagem2">Como ele disse, não é seguro, não por telefone
				</fala>
				<fala personagem="personagem1">Não deixarei que me faças outra vez
					prisioneiro da minha própria paranóia.
				</fala>
				<fala personagem="personagem2">Se não és paranóico precisas de mim mais do
					que calculas. Nós tínhamos um acordo. Querias falar com ele? Eu
					tratei disso. Não tenho culpa que seja maluquinho da cabeça.
				</fala>
				Ele espera que eu acredite nisto? Acabámos mesmo de falar com homem
				mais procurado do planeta?
			</cenas>
		</episódios>
	</temporadas>
</guião>
